# my:
#     greeting: Welcome to Great Learning
#     list:
#         values: apple, banana, mango
my:
 greeting: Welcome to Springboot cloud configuration manageent
 appName: Config Client 1
 list:
  values: apple, banana, mango
